include:
  - project: 'aeontronix/templates/gitlab-pipelines'
    file: 'maven-oss-lib.yml'

docs:
  only:
    - master
    - /^rel-.*$/
  allow_failure: false
  stage: Build
  except:
    refs:
      - tags
    variables:
      - $SKIP_DOCS
  script:
    - source /usr/bin/prepare-build
    - cd docs
    - sh build.sh
