variables:
  PUBLISH_HOMEBREW: "aeontronix/homebrew-enhancedmule.git"
  PUBLISH_HOMEBREW_FILE: "cli/target/enhanced-mule-tools-cli-@version@-dist.tbz2"
  PUBLISH_HOMEBREW_FORMULA: "cli/src/main/assembly/emt.tap"
  PUBLISH_HOMEBREW_FORMULA_NAME: "emt"

include:
  - project: 'aeontronix/commercial-software/ci-pipeline-lib'
    file: 'gitlab/maven-oss-lib.yml'

publish-version:
  stage: build
#  stage: Release
#  needs: [ "build-release-branch", "publish-to-rel-repo" ]
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_BRANCH == /^rel-.*$/
    - if: $CI_COMMIT_BRANCH == /^hotfix-.*$/
  script:
    - !reference [ .scripts, setup ]
    - echo "${POM_REL_VERSION}" > emt_test.version.txt
    - aws cp emt.version.txt s3://static.enhanced-mule.com/versions/emt_test.version.txt
