image: "kloudtek/kt-build-docker-image:latest"

variables:
  MAVEN_OPTS: ""
  MAVEN_FULL_OPTS: "${MAVEN_OPTS} -Dgpg.passphrase=${PGP_PW} -Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: ""
  MAVEN_SNAPSHOT_OPTS: ""
  MAVEN_RELEASES_OPTS: ""
  MAVEN_FULLCLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true ${MAVEN_CLI_OPTS} "

cache:
  paths:
    - $CI_PROJECT_DIR/.m2/repository

include:
  - project: 'aeontronix/templates/gitlab-pipelines'
    file: 'shared.yml'

build-maven-release-candidates:
  stage: Build
  except:
    - tags
  only:
    - master
    - /^rel-.*$/
  script:
    - echo "Running Prepare Build Script"
    - source /usr/bin/prepare-build
    - echo "Building Library"
    - mvn ${MAVEN_FULLCLI_OPTS} deploy ${MAVEN_SNAPSHOT_OPTS} ${MAVEN_FULL_OPTS}
  artifacts:
    paths:
      - pom.xml
      - "*/pom.xml"
      - "**/*.jar"
    exclude:
      - ".m2/**"

build-maven-other:
  stage: Build
  script:
    - 'mvn $MAVEN_CLI_OPTS verify'
  except:
    - tags
    - master
    - /^rel-.*$/

publish-release:
  dependencies:
    - build-maven-release-candidates
    - release-approve
  only:
    - master
    - /^rel-.*$/
  allow_failure: false
  stage: Release
  except:
    refs:
      - tags
    variables:
      - $SKIP_REL
  script:
    - source /usr/bin/prepare-build
    - git remote set-url origin git@gitlab.com:${CI_PROJECT_PATH}.git
    - git branch temp-release-${POM_REL_VERSION}
    - mvn $MAVEN_CLI_OPTS versions:set ${MAVEN_FULL_OPTS} -DprocessAllModules=true -DgroupId='*' -DartifactId='*' -DoldVersion='*' -DnewVersion=${POM_REL_VERSION}
    - git commit -a -m "release ${POM_REL_VERSION}"
    - mvn ${MAVEN_FULLCLI_OPTS} deploy ${MAVEN_FULL_OPTS} ${MAVEN_RELEASES_OPTS}
    - source cli/release.sh
    - git tag v${POM_REL_VERSION}
    - git checkout ${CI_COMMIT_REF_NAME}
    - git branch -D temp-release-${POM_REL_VERSION}
    - git push --tags
  artifacts:
    paths:
      - target/*.zip
      - target/*.jar
      - target/*.exe
      - target/*.tar.gz
      - target/*.tbz2
      - target/*.pdf

pages:
  stage: Publish Docs
  dependencies:
    - publish-release
  only:
    refs:
      - master
    variables:
      - $BUILDSITE == 'true'
  script:
    - source /usr/bin/prepare-build
    - echo building wehsite
    - mvn ${MAVEN_FULLCLI_OPTS} site site:deploy
  artifacts:
    paths:
      - public
